### PR TITLE
Addressing #7: Updated the Sidebar

### PR DESCRIPTION
**Pull request by manan2501**
## This is the updated Sidebar:
image

### CODE REVIEW

**Review by HemangNakarani — CHANGES_REQUESTED** [review]
You just needed to change the title and icons in the Routs.js file, but you have changed components also, because of this I couldn't open even the Login Page. So now do one thing, revert changes for components just change title and icons, if you need to add more routes the just use some components again.

**Comment by manan2501** [comment]
> You just needed to change the title and icons in the Routs.js file, but you have changed components also, because of this I couldn't open even the Login Page. So now do one thing, revert changes for components just change title and icons, if you need to add more routes the just use some components again.

It was due to the removal of the Login and register route, I have added them again to the route file.
image

**Comment by manan2501** [comment]
I have also made a little change in the sidebar component, please check
image

**Review by HemangNakarani — CHANGES_REQUESTED** [review]
@manan2501 You don't need to do changes in Sidebar.js file, Just do as it was, because it's not good practice to render components conditionally. Please remove that condition, and just change components as they were before. Changes will be made in the Routes.js file only. If there are more options then just reuse the components for temporary use. By doing this we can just change an already available file, we will not need to make new components.

Good work otherwise !!

**Comment by manan2501** [comment]
Ok, done. Please check it.

**Review by HemangNakarani — APPROVED** [review]
***Good Work !!!***

**Comment by HemangNakarani** [comment]
give @manan2501 25 points

**Pull request merged**
